/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StoreName = IDL.Text;
export const ProductName = IDL.Text;
export const Price = IDL.Float64;
export const DiscountPercentage = IDL.Float64;
export const ProductCategory = IDL.Text;
export const Address = IDL.Text;
export const City = IDL.Text;
export const State = IDL.Text;
export const ZipCode = IDL.Nat;
export const Coordinates = IDL.Tuple(IDL.Float64, IDL.Float64);
export const AvailabilityStatus = IDL.Variant({
  'limited_quantity' : IDL.Null,
  'available' : IDL.Null,
  'out_of_stock' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const StoreLocation = IDL.Record({
  'zip_code' : ZipCode,
  'city' : City,
  'state' : State,
  'address' : Address,
  'coordinates' : Coordinates,
});
export const ClearanceItem = IDL.Record({
  'id' : IDL.Nat,
  'product_category' : ProductCategory,
  'availability_status' : AvailabilityStatus,
  'clearance_price' : Price,
  'discount_percentage' : DiscountPercentage,
  'product_name' : ProductName,
  'store_name' : StoreName,
  'original_price' : Price,
  'last_update' : Timestamp,
  'store_location' : StoreLocation,
});

export const idlService = IDL.Service({
  'addClearanceItem' : IDL.Func(
      [
        StoreName,
        ProductName,
        Price,
        Price,
        DiscountPercentage,
        ProductCategory,
        Address,
        City,
        State,
        ZipCode,
        Coordinates,
        AvailabilityStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteClearanceItem' : IDL.Func([IDL.Nat], [], []),
  'getClearanceItem' : IDL.Func([IDL.Nat], [ClearanceItem], ['query']),
  'getClearanceItemsByLocation' : IDL.Func(
      [City, State],
      [IDL.Vec(ClearanceItem)],
      ['query'],
    ),
  'getClearanceItemsByPriceRange' : IDL.Func(
      [Price, Price],
      [IDL.Vec(ClearanceItem)],
      ['query'],
    ),
  'getClearanceItemsByStore' : IDL.Func(
      [StoreName],
      [IDL.Vec(ClearanceItem)],
      ['query'],
    ),
  'updateClearanceItem' : IDL.Func(
      [
        IDL.Nat,
        StoreName,
        ProductName,
        Price,
        Price,
        DiscountPercentage,
        ProductCategory,
        Address,
        City,
        State,
        ZipCode,
        Coordinates,
        AvailabilityStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StoreName = IDL.Text;
  const ProductName = IDL.Text;
  const Price = IDL.Float64;
  const DiscountPercentage = IDL.Float64;
  const ProductCategory = IDL.Text;
  const Address = IDL.Text;
  const City = IDL.Text;
  const State = IDL.Text;
  const ZipCode = IDL.Nat;
  const Coordinates = IDL.Tuple(IDL.Float64, IDL.Float64);
  const AvailabilityStatus = IDL.Variant({
    'limited_quantity' : IDL.Null,
    'available' : IDL.Null,
    'out_of_stock' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const StoreLocation = IDL.Record({
    'zip_code' : ZipCode,
    'city' : City,
    'state' : State,
    'address' : Address,
    'coordinates' : Coordinates,
  });
  const ClearanceItem = IDL.Record({
    'id' : IDL.Nat,
    'product_category' : ProductCategory,
    'availability_status' : AvailabilityStatus,
    'clearance_price' : Price,
    'discount_percentage' : DiscountPercentage,
    'product_name' : ProductName,
    'store_name' : StoreName,
    'original_price' : Price,
    'last_update' : Timestamp,
    'store_location' : StoreLocation,
  });
  
  return IDL.Service({
    'addClearanceItem' : IDL.Func(
        [
          StoreName,
          ProductName,
          Price,
          Price,
          DiscountPercentage,
          ProductCategory,
          Address,
          City,
          State,
          ZipCode,
          Coordinates,
          AvailabilityStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteClearanceItem' : IDL.Func([IDL.Nat], [], []),
    'getClearanceItem' : IDL.Func([IDL.Nat], [ClearanceItem], ['query']),
    'getClearanceItemsByLocation' : IDL.Func(
        [City, State],
        [IDL.Vec(ClearanceItem)],
        ['query'],
      ),
    'getClearanceItemsByPriceRange' : IDL.Func(
        [Price, Price],
        [IDL.Vec(ClearanceItem)],
        ['query'],
      ),
    'getClearanceItemsByStore' : IDL.Func(
        [StoreName],
        [IDL.Vec(ClearanceItem)],
        ['query'],
      ),
    'updateClearanceItem' : IDL.Func(
        [
          IDL.Nat,
          StoreName,
          ProductName,
          Price,
          Price,
          DiscountPercentage,
          ProductCategory,
          Address,
          City,
          State,
          ZipCode,
          Coordinates,
          AvailabilityStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };