/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Address = string;
export type AvailabilityStatus = { 'limited_quantity' : null } |
  { 'available' : null } |
  { 'out_of_stock' : null };
export type City = string;
export interface ClearanceItem {
  'id' : bigint,
  'product_category' : ProductCategory,
  'availability_status' : AvailabilityStatus,
  'clearance_price' : Price,
  'discount_percentage' : DiscountPercentage,
  'product_name' : ProductName,
  'store_name' : StoreName,
  'original_price' : Price,
  'last_update' : Timestamp,
  'store_location' : StoreLocation,
}
export type Coordinates = [number, number];
export type DiscountPercentage = number;
export type Price = number;
export type ProductCategory = string;
export type ProductName = string;
export type State = string;
export interface StoreLocation {
  'zip_code' : ZipCode,
  'city' : City,
  'state' : State,
  'address' : Address,
  'coordinates' : Coordinates,
}
export type StoreName = string;
export type Timestamp = bigint;
export type ZipCode = bigint;
export interface _SERVICE {
  'addClearanceItem' : ActorMethod<
    [
      StoreName,
      ProductName,
      Price,
      Price,
      DiscountPercentage,
      ProductCategory,
      Address,
      City,
      State,
      ZipCode,
      Coordinates,
      AvailabilityStatus,
    ],
    bigint
  >,
  'deleteClearanceItem' : ActorMethod<[bigint], undefined>,
  'getClearanceItem' : ActorMethod<[bigint], ClearanceItem>,
  'getClearanceItemsByLocation' : ActorMethod<
    [City, State],
    Array<ClearanceItem>
  >,
  'getClearanceItemsByPriceRange' : ActorMethod<
    [Price, Price],
    Array<ClearanceItem>
  >,
  'getClearanceItemsByStore' : ActorMethod<[StoreName], Array<ClearanceItem>>,
  'updateClearanceItem' : ActorMethod<
    [
      bigint,
      StoreName,
      ProductName,
      Price,
      Price,
      DiscountPercentage,
      ProductCategory,
      Address,
      City,
      State,
      ZipCode,
      Coordinates,
      AvailabilityStatus,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];