/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ClearanceItem {
    id: bigint;
    product_category: ProductCategory;
    availability_status: AvailabilityStatus;
    clearance_price: Price;
    discount_percentage: DiscountPercentage;
    product_name: ProductName;
    store_name: StoreName;
    original_price: Price;
    last_update: Timestamp;
    store_location: StoreLocation;
}
export interface StoreLocation {
    zip_code: ZipCode;
    city: City;
    state: State;
    address: Address;
    coordinates: Coordinates;
}
export type Coordinates = [number, number];
export type StoreName = string;
export type City = string;
export type ProductName = string;
export type Price = number;
export type ZipCode = bigint;
export type DiscountPercentage = number;
export type State = string;
export type ProductCategory = string;
export type Address = string;
export enum AvailabilityStatus {
    limited_quantity = "limited_quantity",
    available = "available",
    out_of_stock = "out_of_stock"
}
export interface backendInterface {
    addClearanceItem(storeName: StoreName, productName: ProductName, originalPrice: Price, clearancePrice: Price, discountPercentage: DiscountPercentage, productCategory: ProductCategory, address: Address, city: City, state: State, zipCode: ZipCode, coordinates: Coordinates, availabilityStatus: AvailabilityStatus): Promise<bigint>;
    deleteClearanceItem(id: bigint): Promise<void>;
    getClearanceItem(id: bigint): Promise<ClearanceItem>;
    getClearanceItemsByLocation(city: City, state: State): Promise<Array<ClearanceItem>>;
    getClearanceItemsByPriceRange(minPrice: Price, maxPrice: Price): Promise<Array<ClearanceItem>>;
    getClearanceItemsByStore(storeName: StoreName): Promise<Array<ClearanceItem>>;
    updateClearanceItem(id: bigint, storeName: StoreName, productName: ProductName, originalPrice: Price, clearancePrice: Price, discountPercentage: DiscountPercentage, productCategory: ProductCategory, address: Address, city: City, state: State, zipCode: ZipCode, coordinates: Coordinates, availabilityStatus: AvailabilityStatus): Promise<void>;
}
import type { AvailabilityStatus as _AvailabilityStatus, ClearanceItem as _ClearanceItem, DiscountPercentage as _DiscountPercentage, Price as _Price, ProductCategory as _ProductCategory, ProductName as _ProductName, StoreLocation as _StoreLocation, StoreName as _StoreName, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addClearanceItem(arg0: StoreName, arg1: ProductName, arg2: Price, arg3: Price, arg4: DiscountPercentage, arg5: ProductCategory, arg6: Address, arg7: City, arg8: State, arg9: ZipCode, arg10: Coordinates, arg11: AvailabilityStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addClearanceItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_AvailabilityStatus_n1(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClearanceItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_AvailabilityStatus_n1(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async deleteClearanceItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClearanceItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClearanceItem(arg0);
            return result;
        }
    }
    async getClearanceItem(arg0: bigint): Promise<ClearanceItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getClearanceItem(arg0);
                return from_candid_ClearanceItem_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClearanceItem(arg0);
            return from_candid_ClearanceItem_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClearanceItemsByLocation(arg0: City, arg1: State): Promise<Array<ClearanceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClearanceItemsByLocation(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClearanceItemsByLocation(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClearanceItemsByPriceRange(arg0: Price, arg1: Price): Promise<Array<ClearanceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClearanceItemsByPriceRange(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClearanceItemsByPriceRange(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClearanceItemsByStore(arg0: StoreName): Promise<Array<ClearanceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClearanceItemsByStore(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClearanceItemsByStore(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClearanceItem(arg0: bigint, arg1: StoreName, arg2: ProductName, arg3: Price, arg4: Price, arg5: DiscountPercentage, arg6: ProductCategory, arg7: Address, arg8: City, arg9: State, arg10: ZipCode, arg11: Coordinates, arg12: AvailabilityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClearanceItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_AvailabilityStatus_n1(this._uploadFile, this._downloadFile, arg12));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClearanceItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_AvailabilityStatus_n1(this._uploadFile, this._downloadFile, arg12));
            return result;
        }
    }
}
function from_candid_AvailabilityStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ClearanceItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClearanceItem): ClearanceItem {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    product_category: _ProductCategory;
    availability_status: _AvailabilityStatus;
    clearance_price: _Price;
    discount_percentage: _DiscountPercentage;
    product_name: _ProductName;
    store_name: _StoreName;
    original_price: _Price;
    last_update: _Timestamp;
    store_location: _StoreLocation;
}): {
    id: bigint;
    product_category: ProductCategory;
    availability_status: AvailabilityStatus;
    clearance_price: Price;
    discount_percentage: DiscountPercentage;
    product_name: ProductName;
    store_name: StoreName;
    original_price: Price;
    last_update: Timestamp;
    store_location: StoreLocation;
} {
    return {
        id: value.id,
        product_category: value.product_category,
        availability_status: from_candid_AvailabilityStatus_n5(_uploadFile, _downloadFile, value.availability_status),
        clearance_price: value.clearance_price,
        discount_percentage: value.discount_percentage,
        product_name: value.product_name,
        store_name: value.store_name,
        original_price: value.original_price,
        last_update: value.last_update,
        store_location: value.store_location
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limited_quantity: null;
} | {
    available: null;
} | {
    out_of_stock: null;
}): AvailabilityStatus {
    return "limited_quantity" in value ? AvailabilityStatus.limited_quantity : "available" in value ? AvailabilityStatus.available : "out_of_stock" in value ? AvailabilityStatus.out_of_stock : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClearanceItem>): Array<ClearanceItem> {
    return value.map((x)=>from_candid_ClearanceItem_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AvailabilityStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): {
    limited_quantity: null;
} | {
    available: null;
} | {
    out_of_stock: null;
} {
    return value == AvailabilityStatus.limited_quantity ? {
        limited_quantity: null
    } : value == AvailabilityStatus.available ? {
        available: null
    } : value == AvailabilityStatus.out_of_stock ? {
        out_of_stock: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
